apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-rollouts-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: argo-rollouts
    prometheus: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - argo-rollouts
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
