apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: retail-store-slack-webhook
  namespace: retail-store
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: slack-webhook
  data:
    - secretKey: webhook-url
      remoteRef:
        key: dev/retail-store/slack
        property: webhook-url
