# Dev environment: 1 replica per service (minimal footprint)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-ui
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-catalog
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-cart
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-orders
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-checkout
spec:
  replicas: 1
